name: Build XMRig Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Download & Build Dependencies
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cd scripts
        call build_deps.cmd

    - name: Configure CMake
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DXMRIG_DEPS=scripts/deps

    - name: Build XMRig
      shell: cmd
      run: |
        cd build
        cmake --build . --config Release

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-zero-fee-windows
        path: build/Release/xmrig.exe
